# Generated by Django 3.2 on 2021-04-18 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modeified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='loan.basemodel')),
                ('phone', models.CharField(max_length=10)),
                ('address', models.JSONField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('loan.basemodel',),
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='loan.basemodel')),
                ('loan_type', models.CharField(choices=[('house', 'Home Loan'), ('car', 'Car loan'), ('personal', 'personal')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=20)),
                ('tenure', models.IntegerField()),
                ('interest_rate', models.DecimalField(decimal_places=10, max_digits=20)),
                ('emi', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('principal_amount', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('rejected', 'Rejeted'), ('approved', 'Approved')], default='new', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.client')),
            ],
            bases=('loan.basemodel',),
        ),
    ]
