# Generated by Django 3.2 on 2021-04-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_auto_20210428_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(choices=[('home', 'Home Loan'), ('car', 'Car loan'), ('personal', 'personal')], max_length=50),
        ),
    ]
